runtime: python311
env: flex
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# The python_version specification is not necessary here since the runtime already specifies it
# runtime_config:
#   python_version: 3

handlers:
  - url: /static
    static_dir: static  # This serves files in the static directory at /static

  - url: /.*
    script: auto  # This directs all other requests to your FastAPI application